// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpszlesmoemxsuqmqmhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc3psZXNtb2VteHN1cW1xbWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzIxMDYsImV4cCI6MjA2MTI0ODEwNn0.ezsaMp2z8pe3vz5Z7M5glxBaUlrFJ5JDRzvCjEl6p6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);